name: Update Pastebin Password

on:
  schedule:
    - cron: "0 * * * *"  # Jalan setiap jam
  workflow_dispatch:  # Bisa dijalankan manual juga

jobs:
  update-pastebin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          PASTEBIN_API_KEY: ${{ secrets.PASTEBIN_API_KEY }}
          PASTEBIN_USER_KEY: ${{ secrets.PASTEBIN_USER_KEY }}
          PASTE_ID_LINKPASSWORD: ${{ secrets.PASTE_ID_LINKPASSWORD }}
          PASTE_ID_LINKKONTEN: ${{ secrets.PASTE_ID_LINKKONTEN }}
        run: python scripts/update_pastebin.py
